apiVersion: apps/v1
kind: Deployment
metadata:
  name: reasonml-postgres
  labels:
    app: reasonml-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reasonml-postgres
  template:
    metadata:
      labels:
        app: reasonml-postgres
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: reasonml-postgres
          image: gcr.io/PROJECT_ID/APPLICATION_NAME:TAG
          ports:
            - containerPort: 8008
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"

---
kind: Service
apiVersion: v1
metadata:
  name: reasonml-postgres
spec:
  selector:
    app: reasonml-postgres
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
